#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "เกิดข้อผิดพลาด: กรุณาเข้าสู่ระบบด้วย root : sudo -i ก่อนลงสคริปต์" 2>&1
  exit 1
fi

MYIP=$(wget -qO- http://whatismyip.akamai.com/)

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

apt update
apt-get -y install ufw
apt-get -y install sudo

apt -y install curl gnupg2 wget unzip
apt -y install neofetch
echo "clear" >> .bash_profile
echo "neofetch" >> .bash_profile

echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] http://repo.mongodb.org/apt/debian buster/mongodb-org/6.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
echo "deb https://repo.pritunl.com/stable/apt buster main" > /etc/apt/sources.list.d/pritunl.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 6A26B1AE64C3C388
sudo apt --assume-yes install gnupg
curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \--dearmor
apt -y install dirmngr
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7AE645C0CF8E292A
apt update
apt --assume-yes install pritunl mongodb-server
systemctl start pritunl mongodb
systemctl enable pritunl mongodb

cd
# setting port ssh
sed -i '/Port 22/a Port 22' /etc/ssh/sshd_config
sed -i 's/Port 22/Port 22/g' /etc/ssh/sshd_config
service ssh restart

# install dropbear
apt -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=143/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 12000 -p 115 -p 109"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service dropbear restart

# Banner
wget -O /etc/issue.net "https://raw.githubusercontent.com/PiTOn-0/Alone/master/Banner"
echo "Banner /etc/issue.net" >> /etc/ssh/sshd_config
sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear
service ssh restart
service dropbear restart

cd /usr/bin
wget -O /usr/local/bin/m "https://raw.githubusercontent.com/PiTOn-0/Alone/master/menu"
wget -O /usr/local/bin/01 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/edit_squid"
wget -O /usr/local/bin/02 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/squid-restart"
wget -O /usr/local/bin/03 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/User-New"
wget -O /usr/local/bin/04 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/User"
wget -O /usr/local/bin/05 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/online"
wget -O /usr/local/bin/06 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/Delete-user"
wget -O /usr/local/bin/07 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/RestartSSH"

chmod +x /usr/local/bin/m
chmod +x /usr/local/bin/01
chmod +x /usr/local/bin/02
chmod +x /usr/local/bin/03
chmod +x /usr/local/bin/04
chmod +x /usr/local/bin/05
chmod +x /usr/local/bin/06
chmod +x /usr/local/bin/07

apt -y install squid

cp /etc/squid/squid.conf /etc/squid/squid.conf.orig
echo "acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl CONNECT method CONNECT

acl SSH dst $MYIP-$MYIP/255.255.255.255

http_access allow SSH
http_access allow localhost manager
http_access deny manager
http_access allow localnet
http_access allow localhost
http_access deny all

http_port 8080
http_port 8000
http_port 3128

cache_store_log none
cache_log /dev/null
logfile_rotate 0

via off
forwarded_for off
dns_v4_first on
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
visible_hostname Phanudet" > /etc/squid/squid.conf

/etc/init.d/squid start
/etc/init.d/squid restart

sudo ufw allow http
sudo ufw allow https
sudo ufw allow ssh
sudo ufw allow 143/tcp
sudo ufw allow 12000/tcp
sudo ufw allow 115/tcp
sudo ufw allow 109/tcp
sudo ufw allow 143/udp
sudo ufw allow 12000/udp
sudo ufw allow 115/udp
sudo ufw allow 109/udp
sudo ufw allow 8080
sudo ufw allow 8000
sudo ufw allow 3128

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable

clear
echo ""
echo " ========= • ≧ SCRIPT INSTALL AUTO ≦ • ========="
echo "        ------ • ≧ ติดตั้งสำเร็จ..! ≦ • ------"
echo ""
echo " ➢  สคริปต์ใช้งานฟรี ความคุมเซิร์ฟเวอร์ด้วยระบบ PRITUNL."
echo " ➢  เมนู : m"
echo ""
echo "• Squid Proxy : $MYIP"
echo "• Proxy Port  : 8080,8000,3128"
echo "• Pritunl Websites https://$MYIP"
echo ""
pritunl setup-key
echo ""
