#!/bin/bash
#ลบ บันชี SSH

clear
echo -e ""
read -p "ใส่ชื่อผู้ใช้ที่จะลบ: " Users

if getent passwd $Users > /dev/null 2>&1; then
        userdel $Users
        echo -e "$Users ลบเรียบร้อย อย่าลืม Restart ด้วยน่าาา."
else
        echo -e "$Users เกิดข้อผิดพลาด ไม่มีชื่อผู้ใช้นี้ในระบบ : m"
fi
