#!/bin/bash
# Script install PRITUNL

clear
echo -e ""
echo -e "  -------------*          เลือกเมนู ติดตั้ง          *-------------"
echo -e ""
echo -e "                  [1] Ubuntu 18.04 LTS x64"
echo -e ""
echo -e "                  [2] Ubuntu 20.04 LTS x64"
echo -e ""
read -p "   เลือกเมนู [1-2 or m] :  " Alone 
echo -e ""
clear
case $Alone in
		1)
		clear
		wget -O Alone "https://raw.githubusercontent.com/lemon-zaza/Alone/master/ubuntu18"
bash +x Alone

		exit
		;;
		2)
		clear
		wget -O Alone "https://raw.githubusercontent.com/lemon-zaza/Alone/master/ubuntu20"
bash +x Alone

		exit
		;;
		*)
		clear
		exit
		;;
	esac
