#!/bin/bash

clear
echo -e ""
echo -e "============================="
echo -e ""
echo -e " ➢ Command  : Script"
echo -e ""
echo -e "============================="
echo -e ""
echo -e " ➢ 01       : แก้ใข Proxy"
echo -e " ➢ 02       : รีสตาร์ท Proxy"
echo -e " ➢ 03       : เปิดใช้งาน UFW"
echo -e ""
echo -e "============================="
echo -e ""
