#!/bin/bash

clear
echo -e ""
echo -e "============================="
echo -e ""
echo -e " ➢ Donate At 0802686710 thank you."
echo -e " ➢ Command  : Script"
echo -e ""
echo -e " *( 03 ) เมื่อเปิดใช้จะไม่สามารถ login Pritunl ได้ในขณะใช้ server อื่น"
echo -e ""
echo -e "============================="
echo -e ""
echo -e " ➢ 01       : แก้ใข Proxy"
echo -e " ➢ 02       : รีสตาร์ท Proxy"
echo -e " ➢ 03       : เปิดใช้งาน UFW"
echo -e ""
echo -e "============================="
echo -e ""
