#!/bin/bash

/etc/init.d/squid3 restart
systemctl start pritunl mongodb
systemctl restart pritunl mongodb
systemctl enable pritunl mongodb

echo -e ""
echo -e "\033[1;37m Restart เสร็จ \033[1;31m:\033[1;32m m"
echo -e ""
