#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "เกิดข้อผิดพลาด: กรุณาเข้าสู่ระบบด้วย root : sudo -i ก่อนลงสคริปต์" 2>&1
  exit 1
fi

NC='\033[0m'
MYIP=$(wget -qO- http://whatismyip.akamai.com/)

apt update
apt -y install ufw

apt -y install curl gnupg2 wget unzip
apt -y install neofetch
echo "clear" >> .bash_profile
echo "neofetch" >> .bash_profile

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
echo "deb https://repo.pritunl.com/stable/apt bionic main" > /etc/apt/sources.list.d/pritunl.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 6A26B1AE64C3C388
sudo apt --assume-yes install gnupg
curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \--dearmor
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7AE645C0CF8E292A
apt update
apt --assume-yes install pritunl mongodb-server
systemctl start pritunl mongodb
systemctl enable pritunl mongodb

clear
sudo touch /etc/apt/sources.list.d/trusty_sources.list
echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe" > /etc/apt/sources.list.d/trusty_sources.list
apt update

apt -y install squid3=3.3.8-1ubuntu6 squid=3.3.8-1ubuntu6 squid3-common=3.3.8-1ubuntu6
wget -O squid3 https://raw.githubusercontent.com/lemon-zaza/Alone/master/squid3
sudo cp squid3 /etc/init.d/
sudo chmod +x /etc/init.d/squid3
sudo update-rc.d squid3 defaults

cp /etc/squid3/squid.conf /etc/squid3/squid.conf.orig
echo "acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl CONNECT method CONNECT

acl ip_server dst $MYIP-$MYIP/255.255.255.255

http_access allow ip_server
http_access allow localhost manager
http_access deny manager
http_access allow localnet
http_access allow localhost
http_access deny all

http_port 8080

cache_store_log none
cache_log /dev/null
logfile_rotate 0

via off
forwarded_for off
dns_v4_first on
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
visible_hostname Phanudet" > /etc/squid3/squid.conf

/etc/init.d/squid3 start
/etc/init.d/squid3 restart

clear

apt update

ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

apt-get -y install nginx php-fpm php-cli
cd
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
cat > /etc/nginx/nginx.conf <<END
user www-data;
worker_processes 2;
pid /var/run/nginx.pid;
events {
	multi_accept on;
        worker_connections 1024;
}
http {
	autoindex on;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        client_max_body_size 32M;
	client_header_buffer_size 8m;
	large_client_header_buffers 8 8m;
	fastcgi_buffer_size 8m;
	fastcgi_buffers 8 8m;
	fastcgi_read_timeout 600;
        include /etc/nginx/conf.d/*.conf;
}
END
	mkdir -p /home/vps/public_html
	wget -qO- -O /home/vps/public_html/index.html https://raw.githubusercontent.com/lemon-zaza/phanudet/master/www.html
	echo "<?phpinfo(); ?>" > /home/vps/public_html/info.php
	args='$args'
	uri='$uri'
	document_root='$document_root'
	fastcgi_script_name='$fastcgi_script_name'
	cat > /etc/nginx/conf.d/vps.conf <<END
server {
    listen       85;
    server_name  127.0.0.1 localhost;
    access_log /var/log/nginx/vps-access.log;
    error_log /var/log/nginx/vps-error.log error;
    root   /home/vps/public_html;
    location / {
        index  index.html index.htm index.php;
	try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass  127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
END
wget -qO- -O /etc/php/7.2/fpm/pool.d/www.conf https://raw.githubusercontent.com/lemon-zaza/phanudet/master/php
service php7.2-fpm restart
service nginx restart

apt -y install vnstat
wget -qO- -O /etc/vnstat.conf https://raw.githubusercontent.com/lemon-zaza/phanudet/master/vnstat.conf
sudo chown -R vnstat:vnstat /var/lib/vnstat
service vnstat restart

cd /home/vps/public_html/
wget http://www.sqweek.com/sqweek/files/vnstat_php_frontend-1.5.1.tar.gz
tar xf vnstat_php_frontend-1.5.1.tar.gz
rm vnstat_php_frontend-1.5.1.tar.gz
mv vnstat_php_frontend-1.5.1 vnstat
cd vnstat
wget -qO- -O config.php https://raw.githubusercontent.com/lemon-zaza/phanudet/master/config.php
cd

sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw allow 85
sudo ufw allow 8080

clear
cd /usr/bin
wget -O /usr/local/bin/m "https://raw.githubusercontent.com/lemon-zaza/Alone/master/menu"
wget -O /usr/local/bin/01 "https://raw.githubusercontent.com/lemon-zaza/Alone/master/edit1"
wget -O /usr/local/bin/02 "https://raw.githubusercontent.com/lemon-zaza/Alone/master/Restart"
wget -O /usr/local/bin/03 "https://raw.githubusercontent.com/lemon-zaza/Alone/master/ufw"
wget -O /usr/local/bin/04 "https://raw.githubusercontent.com/lemon-zaza/phanudet/master/restart-n-v-p"

chmod +x /usr/local/bin/m
chmod +x /usr/local/bin/01
chmod +x /usr/local/bin/02
chmod +x /usr/local/bin/03
chmod +x /usr/local/bin/04

clear
echo -e ""
echo -e "\E[44;1;45m          ------ • ≧ ติดตั้งสำเร็จ..! ≦ • ------           \E[0m"
echo -e "\033[1;32m*\033[1;33m ความคุมเซิร์ฟเวอร์ด้วยระบบ \033[1;32mPRITUNL."
echo -e "\033[1;32m*\033[1;37mMENU \033[1;31m:\033[1;32m m"
echo -e ""
echo -e "\033[1;32m• \033[1;37mTimezone \033[1;31m: \033[1;32m Thailand"
echo -e "\033[1;32m• \033[1;37mSquid Proxy \033[1;31m: \033[1;32m$MYIP"
echo -e "\033[1;32m• \033[1;37mProxy Port  \033[1;31m: \033[1;32m8080"
echo -e "\033[1;32m• \033[1;36mBy Script  http://$MYIP:85${NC}"
echo -e "\033[1;32m• \033[1;36mBandwidth http://$MYIP:85/vnstat${NC}"
echo -e "\033[1;32m• \033[1;36mPritunl Websites https://$MYIP${NC}"
echo -e ""
pritunl setup-key
echo -e ""
echo -e "\033[1;32mCopy key Go to website"
echo -e ""
echo -ne " \033[1;33m?\033[1;37m${NC} "
