#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "เกิดข้อผิดพลาด: กรุณาเข้าสู่ระบบด้วย root : sudo -i ก่อนลงสคริปต์" 2>&1
  exit 1
fi

MYIP=$(wget -qO- http://whatismyip.akamai.com/)

apt update
apt -y install ufw

apt -y install curl gnupg2 wget unzip
apt -y install neofetch
echo "clear" >> .bash_profile
echo "neofetch" >> .bash_profile

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
echo "deb https://repo.pritunl.com/stable/apt bionic main" > /etc/apt/sources.list.d/pritunl.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 6A26B1AE64C3C388
sudo apt --assume-yes install gnupg
curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \--dearmor
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7AE645C0CF8E292A
apt update
apt --assume-yes install pritunl mongodb-server
systemctl start pritunl mongodb
systemctl enable pritunl mongodb

clear
sudo touch /etc/apt/sources.list.d/trusty_sources.list
echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe" > /etc/apt/sources.list.d/trusty_sources.list
apt update

apt -y install squid3=3.3.8-1ubuntu6 squid=3.3.8-1ubuntu6 squid3-common=3.3.8-1ubuntu6
wget -O squid3 https://raw.githubusercontent.com/PiTOn-0/Alone/master/squid3
sudo cp squid3 /etc/init.d/
sudo chmod +x /etc/init.d/squid3
sudo update-rc.d squid3 defaults

cp /etc/squid3/squid.conf /etc/squid3/squid.conf.orig
echo "acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl CONNECT method CONNECT

acl ip_server dst $MYIP-$MYIP/255.255.255.255

http_access allow ip_server
http_access allow localhost manager
http_access deny manager
http_access allow localnet
http_access allow localhost
http_access deny all

http_port 8080
http_port 3128

cache_store_log none
cache_log /dev/null
logfile_rotate 0

via off
forwarded_for off
dns_v4_first on
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
visible_hostname Phanudet" > /etc/squid3/squid.conf

/etc/init.d/squid3 start
/etc/init.d/squid3 restart

clear
sudo apt update

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config

wget -qO- -O /etc/ssh/sshd_config https://raw.githubusercontent.com/PiTOn-0/lemon/master/sshd_config
systemctl restart sshd
service ssh restart

apt -y install dropbear
sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=143/g' /etc/default/dropbear
sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 12000 -p 115 -p 109"/g' /etc/default/dropbear
echo "/bin/false" >> /etc/shells
echo "/usr/sbin/nologin" >> /etc/shells
service dropbear restart

#Banner
sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear
wget -O /etc/issue.net "https://raw.githubusercontent.com/PiTOn-0/lemon/master/issue.net"
service ssh restart
service dropbear restart

clear
sudo ufw allow 22,143,85,12000,115,109,8080,3128/tcp
sudo ufw allow 22,143,85,12000,115,109,8080,3128/udp
sudo yes | ufw enable

clear
cd /usr/bin
wget -O /usr/local/bin/m "https://raw.githubusercontent.com/PiTOn-0/Alone/master/menu"
wget -O /usr/local/bin/01 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/edit1"
wget -O /usr/local/bin/02 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/Restart"
wget -O /usr/local/bin/03 "https://raw.githubusercontent.com/PiTOn-0/Alone/master/ufw"
wget -O /usr/local/bin/04 "https://raw.githubusercontent.com/PiTOn-0/lemon/master/useradd"
wget -O /usr/local/bin/05 "https://raw.githubusercontent.com/PiTOn-0/lemon/master/user-on"
wget -O /usr/local/bin/06 "https://raw.githubusercontent.com/PiTOn-0/lemon/master/allusers"
wget -O /usr/local/bin/07 "https://raw.githubusercontent.com/PiTOn-0/lemon/master/delete-user"
wget -O /usr/local/bin/08 "https://raw.githubusercontent.com/PiTOn-0/lemon/master/system"

chmod +x /usr/local/bin/m
chmod +x /usr/local/bin/01
chmod +x /usr/local/bin/02
chmod +x /usr/local/bin/03
chmod +x /usr/local/bin/04
chmod +x /usr/local/bin/05
chmod +x /usr/local/bin/06
chmod +x /usr/local/bin/07
chmod +x /usr/local/bin/08

clear
echo -e ""
echo -e "\E[44;1;45m          ------ • ≧ ติดตั้งสำเร็จ..! ≦ • ------           \E[0m"
echo -e "\033[1;32m*\033[1;33m ความคุมเซิร์ฟเวอร์ด้วยระบบ \033[1;32mPRITUNL."
echo -e "\033[1;32m*\033[1;37mMENU \033[1;31m:\033[1;32m m"
echo -e ""
echo -e "\033[1;32m• \033[1;37mTimezone \033[1;31m: \033[1;32m Thailand"
echo -e "\033[1;32m• \033[1;37mSquid Proxy \033[1;31m: \033[1;32m$MYIP"
echo -e "\033[1;32m• \033[1;37mProxy Port  \033[1;31m: \033[1;32m8080,3128"
echo -e "\033[1;32m• \033[1;36mPritunl Websites https://$MYIP"
echo -e ""
pritunl setup-key
echo -e ""
echo -e "\033[1;32mCopy key Go to website"
echo -e ""
echo -ne " \033[1;33m?\033[1;37m "
