#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "เกิดข้อผิดพลาด: กรุณาเข้าสู่ระบบด้วย root : sudo -i ก่อนลงสคริปต์" 2>&1
  exit 1
fi

NC='\033[0m'
MYIP=$(wget -qO- http://whatismyip.akamai.com/)

apt update
apt -y install gpg curl gnupg2 wget unzip software-properties-common apt-transport-https lsb-release ca-certificates
apt -y install neofetch

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/7.0 multiverse" > /etc/apt/sources.list.d/mongodb-org-7.0.list
echo "deb https://repo.pritunl.com/stable/apt bionic main" > /etc/apt/sources.list.d/pritunl.list
curl -fsSL https://pgp.mongodb.com/server-7.0.asc | \sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \--dearmor
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 160D26BB1785BA38
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv-keys 7AE645C0CF8E292A
apt-key adv --armor --export 7AE645C0CF8E292A | sudo tee /etc/apt/trusted.gpg.d/pritunl.asc
apt update
apt --assume-yes install pritunl mongodb-server
systemctl start pritunl mongodb
systemctl enable pritunl mongodb

clear
cat > /etc/ssh/sshd_config <<-END
# By Alone
# phanudet
# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin
# The strategy used for options in the default sshd_config shipped with # OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the # default value.

Include /etc/ssh/sshd_config.d/*.conf

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::                                                       
#HostKey /etc/ssh/ssh_host_rsa_key
#HostKey /etc/ssh/ssh_host_ecdsa_key
#HostKey /etc/ssh/ssh_host_ed25519_key                                  
# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
PermitRootLogin yes
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# Expect .ssh/authorized_keys2 to be disregarded by default in future.
#AuthorizedKeysFile     .ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_h>#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication                                               #IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication yes
#PermitEmptyPasswords no

# Change to yes to enable challenge-response passwords (beware issues w># some PAM modules and threads)
ChallengeResponseAuthentication no
# Kerberos options                                                      #KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes                                              #KerberosGetAFSToken no

# GSSAPI options                                                        #GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no

# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication via ChallengeResponseAuthentication may bypass
# the setting of "PermitRootLogin without-password".
# If you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePAM yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
AcceptEnv LANG LC_*

# override default of no subsystems
Subsystem sftp  /usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#       X11Forwarding no
#       AllowTcpForwarding no
#       PermitTTY no
#       ForceCommand cvs server
END
/etc/init.d/ssh restart

cat > .bash_profile <<-END
clear
neofetch
function ScriptAlone(){
 echo -e ""
 echo -e "\033[1;32m ไอพีเซิร์ฟเวอร์ \033[1;31m: \033[1;37m$MYIP"
 echo -e ""
 sleep 0.5
 echo -e "\033[1;32m TrueMoney Wallet \033[1;37m0802686710"
 sleep 0.5
 echo -e "\033[1;37m Have a nice day.ツ...."
 sleep 0.5
 echo -e "\033[1;37m Script install By Alone OpenMenu\033[1;31m: \033[1;37m m${NC}"
 echo -e ""
 sleep 0.5
}
ScriptAlone
END

sudo touch /etc/apt/sources.list.d/trusty_sources.list
echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe" > /etc/apt/sources.list.d/trusty_sources.list
apt update

apt -y install squid3=3.3.8-1ubuntu6 squid=3.3.8-1ubuntu6 squid3-common=3.3.8-1ubuntu6
wget -O squid3 https://raw.githubusercontent.com/lemon-zaza/Alone/master/squid3
sudo cp squid3 /etc/init.d/
sudo chmod +x /etc/init.d/squid3
sudo update-rc.d squid3 defaults

cp /etc/squid3/squid.conf /etc/squid3/squid.conf.orig
echo "acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl CONNECT method CONNECT

acl ip_server dst $MYIP-$MYIP/255.255.255.255

http_access allow ip_server
http_access allow localhost manager
http_access deny manager
http_access allow localnet
http_access allow localhost
http_access deny all

http_port 8080

cache_store_log none
cache_log /dev/null
logfile_rotate 0

via off
forwarded_for off
dns_v4_first on
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
visible_hostname Phanudet" > /etc/squid3/squid.conf

/etc/init.d/squid3 start
/etc/init.d/squid3 restart

clear

apt update

ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

apt-get -y install nginx php-fpm php-cli
cd
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
cat > /etc/nginx/nginx.conf <<END
user www-data;
worker_processes 2;
pid /var/run/nginx.pid;
events {
	multi_accept on;
        worker_connections 1024;
}
http {
	autoindex on;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        client_max_body_size 32M;
	client_header_buffer_size 8m;
	large_client_header_buffers 8 8m;
	fastcgi_buffer_size 8m;
	fastcgi_buffers 8 8m;
	fastcgi_read_timeout 600;
        include /etc/nginx/conf.d/*.conf;
}
END
	mkdir -p /home/vps/public_html
	wget -qO- -O /home/vps/public_html/index.html https://raw.githubusercontent.com/lemon-zaza/phanudet/master/www.html
	echo "<?phpinfo(); ?>" > /home/vps/public_html/info.php
	args='$args'
	uri='$uri'
	document_root='$document_root'
	fastcgi_script_name='$fastcgi_script_name'
	cat > /etc/nginx/conf.d/vps.conf <<END
server {
    listen       85;
    server_name  127.0.0.1 localhost;
    access_log /var/log/nginx/vps-access.log;
    error_log /var/log/nginx/vps-error.log error;
    root   /home/vps/public_html;
    location / {
        index  index.html index.htm index.php;
	try_files $uri $uri/ /index.php?$args;
    }
    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass  127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
END
wget -qO- -O /etc/php/7.2/fpm/pool.d/www.conf https://raw.githubusercontent.com/lemon-zaza/phanudet/master/php
service php7.2-fpm restart
service nginx restart

apt -y install vnstat
wget -qO- -O /etc/vnstat.conf https://raw.githubusercontent.com/lemon-zaza/phanudet/master/vnstat.conf
sudo chown -R vnstat:vnstat /var/lib/vnstat
service vnstat restart

cd /home/vps/public_html/
wget http://www.sqweek.com/sqweek/files/vnstat_php_frontend-1.5.1.tar.gz
tar xf vnstat_php_frontend-1.5.1.tar.gz
rm vnstat_php_frontend-1.5.1.tar.gz
mv vnstat_php_frontend-1.5.1 vnstat
cd vnstat
wget -qO- -O config.php https://raw.githubusercontent.com/lemon-zaza/phanudet/master/config.php
cd

sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw allow 85
sudo ufw allow 8080

clear
cd /usr/bin
wget -O /usr/local/bin/m "https://raw.githubusercontent.com/lemon-zaza/Alone/master/menu"
wget -O /usr/local/bin/01 "https://raw.githubusercontent.com/lemon-zaza/Alone/master/edit1"
wget -O /usr/local/bin/02 "https://raw.githubusercontent.com/lemon-zaza/Alone/master/Restart"
wget -O /usr/local/bin/03 "https://raw.githubusercontent.com/lemon-zaza/Alone/master/ufw"
wget -O /usr/local/bin/04 "https://raw.githubusercontent.com/lemon-zaza/phanudet/master/restart-n-v-p"
wget -O /usr/local/bin/05 "https://raw.githubusercontent.com/lemon-zaza/phanudet/master/login"
wget -O /usr/local/bin/06 "https://raw.githubusercontent.com/lemon-zaza/phanudet/master/spark01"
wget -O /usr/local/bin/SetReboot "https://raw.githubusercontent.com/lemon-zaza/phanudet/master/SetReboot"
wget -O /usr/local/bin/07 "https://raw.githubusercontent.com/lemon-zaza/phanudet/master/ufwOff"

chmod +x /usr/local/bin/m
chmod +x /usr/local/bin/01
chmod +x /usr/local/bin/02
chmod +x /usr/local/bin/03
chmod +x /usr/local/bin/04
chmod +x /usr/local/bin/05
chmod +x /usr/local/bin/06
chmod +x /usr/local/bin/07
chmod +x /usr/local/bin/SetReboot
cd

clear
echo -e ""
echo -e "\E[44;1;45m          ------ • ≧ ติดตั้งสำเร็จ..! ≦ • ------           \E[0m"
echo -e "\033[1;32m*\033[1;33m ความคุมเซิร์ฟเวอร์ด้วยระบบ \033[1;32mPRITUNL."
echo -e "\033[1;32m*\033[1;37mMENU \033[1;31m:\033[1;32m m"
echo -e ""
echo -e "\033[1;32m• \033[1;37mTimezone \033[1;31m: \033[1;32m Thailand"
echo -e "\033[1;32m• \033[1;37mSquid Proxy \033[1;31m: \033[1;32m$MYIP"
echo -e "\033[1;32m• \033[1;37mProxy Port  \033[1;31m: \033[1;32m8080"
echo -e "\033[1;32m• \033[1;36mBy Script  http://$MYIP:85${NC}"
echo -e "\033[1;32m• \033[1;36mBandwidth http://$MYIP:85/vnstat${NC}"
echo -e "\033[1;32m• \033[1;36mPritunl Websites https://$MYIP${NC}"
echo -e ""
pritunl setup-key
echo -e ""
echo -e "\033[1;32mCopy key Go to website"
echo -e ""
rm -rf /root/.bash_history && history -c && echo '' > /var/log/syslog
echo ""
echo -e "\033[1;32m ล้างบันทึกทั้งหมดจากการติดตั้ง"
sleep 0.5
echo -e "\033[1;32m เซิร์ฟเวอร์จะรีบูตภายใน 5 วินาที${NC}"
sleep 5
rm -f setup*
lemon_zaza
exit 1
