#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "เกิดข้อผิดพลาด: กรุณาเข้าสู่ระบบด้วย root : sudo -i ก่อนลงสคริปต์" 2>&1
  exit 1
fi

MYIP=$(wget -qO- http://whatismyip.akamai.com/)

apt update
apt-get -y install ufw
apt-get -y install sudo

apt -y install curl gnupg2 wget unzip
apt -y install neofetch
echo "clear" >> .bash_profile
echo "neofetch" >> .bash_profile

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" > /etc/apt/sources.list.d/mongodb-org-6.0.list
echo "deb https://repo.pritunl.com/stable/apt focal main" > /etc/apt/sources.list.d/pritunl.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 6A26B1AE64C3C388
sudo apt --assume-yes install gnupg
curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \--dearmor
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7AE645C0CF8E292A
gpg --armor --export 7AE645C0CF8E292A | sudo tee /etc/apt/trusted.gpg.d/pritunl.asc
apt update
apt --assume-yes install pritunl mongodb-server
systemctl start pritunl mongodb
systemctl enable pritunl mongodb

apt -y install squid

cp /etc/squid/squid.conf /etc/squid/squid.conf.orig
echo "acl localnet src 0.0.0.1-0.255.255.255
acl localnet src 10.0.0.0/8
acl localnet src 100.64.0.0/10
acl localnet src 169.254.0.0/16
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80          # http
acl Safe_ports port 21          # ftp
acl Safe_ports port 443         # https
acl Safe_ports port 70          # gopher
acl Safe_ports port 210         # wais
acl Safe_ports port 1025-65535  # unregistered ports
acl Safe_ports port 280         # http-mgmt
acl Safe_ports port 488         # gss-http
acl Safe_ports port 591         # filemaker
acl Safe_ports port 777         # multiling http
acl CONNECT method CONNECT

acl ip_server dst $MYIP-$MYIP/255.255.255.255

http_access allow ip_server
http_access allow localhost manager
http_access deny manager
http_access allow localnet
http_access allow localhost
http_access deny all

http_port 8080
http_port 3128

cache_store_log none
cache_log /dev/null
logfile_rotate 0

via off
forwarded_for off
dns_v4_first on
refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
visible_hostname Phanudet" > /etc/squid/squid.conf

/etc/init.d/squid start
/etc/init.d/squid restart

sudo ufw allow ssh
sudo ufw allow 8080
sudo ufw allow 3128

clear
echo ""
echo " ========= • ≧ SCRIPT INSTALL AUTO ≦ • ========="
echo "        ------ • ≧ ติดตั้งสำเร็จ..! ≦ • ------"
echo ""
echo " ➢ ความคุมเซิร์ฟเวอร์ด้วยระบบ PRITUNL."
echo ""
echo "• Squid Proxy : $MYIP"
echo "• Proxy Port  : 8080,3128"
echo "• Pritunl Websites https://$MYIP"
echo ""
pritunl setup-key
echo ""
