#!/bin/bash

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable

echo ""
echo "  เสร็จ : m"
echo ""
echo "  ตรวจเช็ค  ufw Command."
echo ""
echo "  sudo ufw status verbose"
echo "  sudo systemctl status ufw.service"
echo ""
