#!/bin/bash

sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo yes | ufw enable

echo -e ""
echo -e "\033[1;37m  เสร็จ\033[1;31m :\033[1;32m m"
echo -e ""
echo -e "\033[1;32m  ตรวจเช็ค  ufw Command."
echo -e ""
echo -e "\033[1;35m  sudo ufw status verbose"
echo -e "\033[1;35m  sudo systemctl status ufw.service"
echo -e ""
echo -ne " \033[1;33m?\033[1;37m "
