#!/bin/bash
# User SSH

clear
echo -e ""
echo -e " ========== สร้างบัญชี SSH =========="
echo -e ""
read -p " ➢ ชื่อผู้ใช้  : " Login
read -p " ➢ รหัสผ่าน : " Pass
read -p " ➢ หมดอายุ (กำหนดวัน): " Bangkok

IP=`dig +short myip.opendns.com @resolver1.opendns.com`
useradd -e `date -d "$Bangkok days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null

clear
echo -e ""
echo -e " ========== บันชี SSH =========="
echo -e ""
echo -e " ➢  เซิร์ฟเวอร์ : $IP"
echo -e " ➢  พ็อต     : 22"
echo -e " ➢  พร๊อกซี่   : 8080,3128"
echo -e " ➢  ชื่อผู้ใช้   : $Login "
echo -e " ➢  รหัสผ่าน  : $Pass"
echo -e " ➢  วันหมดอายุ: $exp"
echo -e ""
echo -e "============================"
echo -e ""
echo -e " กลับ : m"
echo -e ""
